### ISSUE TITLE
Doesn't run on AMD GPUs on Win because drivers missing VK_KHR_push_descriptor..

### ISSUE THREAD

**Issue by oscarbg** [zeux/niagara#2]
Makes sense to ask to make AMD Vulkan driver comptabile your Vulkan playground?
thanks.

**Comment by zeux** [comment]
I think this should work on Linux on radv drivers since they expose KHR_push_descriptor. Unfortunately, AMD's official driver doesn't do that. IMO not exposing a KHR extension isn't good...

**Comment by zeux** [comment]
I've added support for push descriptor fallback using the regular descriptor update mechanism; code now "works" on latest AMD drivers but, unfortunately, renders nothing; I'll need to investigate why that is separately.
