### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by DonovaneH** [zeux/niagara#22]
i have this error : 

C:\Users\Donovane>C:\Users\Donovane\Desktop\niagara-master\src\Release\niagara.exe C:\Users\Donovane\Desktop\niagara-master\src\Release\monitor.obj
GPU0: NVIDIA GeForce RTX 2060
Selected GPU NVIDIA GeForce RTX 2060
**Assertion failed: rcs, file C:\Users\Donovane\Desktop\niagara-master\src\niagara.cpp, line 547**

how to solve them ?

**Comment by BeastLe9enD** [comment]
Looks like the shaders are not being loaded properly, ensure that all spirv files are inside the C:\Users\Donovane>C:\Users\Donovane\Desktop\niagara-master\src\Release\ directory.

**Comment by JesseRMeyer** [comment]
The code depends upon the working directory being in src.  

The following works for me.
`F:\niagara\src>.\x64\Release\niagara.exe ..\data\kitten.obj`
