### ISSUE TITLE
Backface culling of triangles may cause incorrect culling for thin plates in CAD models. Why?

### ISSUE THREAD

**Issue by Mrxiegiao** [zeux/niagara#40]
// backface culling + zero-area culling
vec2 eb = pb - pa;
vec2 ec = pc - pa;
culled = culled || (eb.x * ec.y <= eb.y * ec.x);
These codes will make mistakes in thin plates when the camera moves.

**Comment by Mrxiegiao** [comment]
no backface culling:
![image](https://github.com/user-attachments/assets/5ef36aec-aa94-40fc-8301-8f4608213357)
backface culling:
![image](https://github.com/user-attachments/assets/d2e0db61-2d98-461e-b4c4-bb2ffa9b7b6c)

**Comment by zeux** [comment]
Is this screenshot from this renderer?

**Comment by Mrxiegiao** [comment]
I use it in my opengl program. it's wrong, and my mesh shader uses the  GL_NV_mesh_shader extension.

**Comment by Mrxiegiao** [comment]
I want to use your renderer to test this model, but it is too large when loading scenes and has some mistakes.

**Comment by zeux** [comment]
Sorry but then I'm not sure what I should do with this issue. The math is correct as far as I know, modulo maybe subpixel snapping that hardware can do before the check, but on your model the triangles look big enough that if that is the result of the test, the vertex positions must not be correctly transformed or tested.
